// src/config/articles.js
// Single source of truth for all articles in Marketing Cloud Arcade

export const ALL_CARDS = [
  {
    id: "sfmc-overview",
    category: "resources",
    level: "beginner",
    url: "/sfmc-overview",
    title_es: "¿Qué es Marketing Cloud Engagement? Guía Completa",
    title_en: "What is Marketing Cloud Engagement? Complete Guide",
    desc_es:
      "Aprende la historia, arquitectura, Studios, Builders y los prerequisitos clave para una implementación exitosa.",
    desc_en:
      "Learn history, architecture, Studios, Builders and the key prerequisites for a successful SFMC implementation.",
    duration: "12 min",
    date: "Sep 2026",
    viewsMin: 4500,
    viewsMax: 9800,
    hot: true,
    featured: true,
    tags: ["#sfmc-overview", "#basics", "#architecture", "#implementation"],
  },
  {
    id: "ssjs-http",
    category: "ssjs",
    level: "intermediate",
    url: "/ssjs-http",
    title_es: "SSJS: Peticiones HTTP GET y POST",
    title_en: "SSJS: HTTP GET & POST Requests",
    desc_es:
      "Conecta SFMC con cualquier API externa usando HTTP.Get() y HTTP.Post() con manejo de errores y OAuth2.",
    desc_en:
      "Connect SFMC with any external API using HTTP.Get() and HTTP.Post() with error handling and OAuth2.",
    duration: "8 min",
    date: "Apr 2025",
    viewsMin: 3000,
    viewsMax: 8000,
    hot: true,
    tags: ["#ssjs", "#http", "#rest-api", "#oauth2"],
  },
  {
    id: "ssjs-upsert",
    category: "ssjs",
    level: "advanced",
    url: "/ssjs-upsert",
    title_es: "SSJS: Upsert de Contactos via REST API",
    title_en: "SSJS: Upsert Contacts via REST API",
    desc_es:
      "Crea y actualiza contactos masivamente en SFMC usando la Contacts REST API y manejo de errores avanzado.",
    desc_en:
      "Create and update contacts in bulk in SFMC using the Contacts REST API with advanced error handling.",
    duration: "12 min",
    date: "Mar 2025",
    viewsMin: 2000,
    viewsMax: 5000,
    hot: true,
    tags: ["#ssjs", "#rest-api", "#upsert", "#contacts"],
    featured: true,
  },
  {
    id: "ssjs-intro",
    category: "ssjs",
    level: "beginner",
    url: "/ssjs-intro",
    title_es: "Introducción a SSJS en SFMC",
    title_en: "Introduction to SSJS in SFMC",
    desc_es:
      "Qué es SSJS, cómo usarlo en Cloud Pages y Script Activities, y cuáles son sus limitaciones.",
    desc_en:
      "What SSJS is, how to use it in Cloud Pages and Script Activities, and what its limitations are.",
    duration: "5 min",
    date: "Jan 2025",
    viewsMin: 1500,
    viewsMax: 4000,
    hot: false,
    tags: ["#ssjs", "#basics", "#cloudpages", "#automation"],
  },
  {
    id: "ssjs-debug",
    category: "ssjs",
    level: "intermediate",
    url: "/ssjs-debug",
    title_es: "SSJS: Logging y Debugging avanzado",
    title_en: "SSJS: Advanced Logging & Debugging",
    desc_es:
      "Estrategias de logging en Data Extensions y técnicas de debug para scripts en producción.",
    desc_en:
      "Logging strategies using Data Extensions and debug techniques for production scripts.",
    duration: "7 min",
    date: "Mar 2025",
    viewsMin: 700,
    viewsMax: 2000,
    hot: false,
    tags: ["#ssjs", "#debugging", "#troubleshooting"],
  },
  {
    id: "amp-intro",
    category: "ampscript",
    level: "beginner",
    url: "/amp-intro",
    title_es: "Introducción a AMPscript: Guía Completa de Fundamentos",
    title_en: "Introduction to AMPscript: Complete Fundamentals Guide",
    desc_es:
      "Aprende qué es AMPscript, dónde se ejecuta en SFMC, ciclo de vida OMM, delimitadores, sintaxis, variables y funciones clave.",
    desc_en:
      "Learn what AMPscript is, where it executes in SFMC, OMM lifecycle, delimiters, syntax, variables and essential functions.",
    duration: "9 min",
    date: "Sep 2026",
    viewsMin: 4000,
    viewsMax: 8900,
    hot: true,
    featured: true,
    tags: ["#ampscript", "#basics", "#emailstudio", "#personalization"],
  },
  {
    id: "sql-dataviews",
    category: "sql",
    level: "beginner",
    url: "/sql-dataviews",
    title_es: "SQL: Introducción a Data Views de SFMC",
    title_en: "SQL: Intro to SFMC Data Views",
    desc_es:
      "Conoce las Data Views más importantes (_Sent, _Open, _Click, _Bounce) y cómo consultarlas con SQL.",
    desc_en:
      "Learn the most important Data Views (_Sent, _Open, _Click, _Bounce) and how to query them with SQL.",
    duration: "8 min",
    date: "Jan 2025",
    viewsMin: 1000,
    viewsMax: 3000,
    hot: false,
    tags: ["#sql", "#dataviews", "#system-tables"],
  },
  {
    id: "sql-engagement",
    category: "sql",
    level: "intermediate",
    url: "/sql-engagement",
    title_es: "SQL: Score de Engagement de Suscriptores",
    title_en: "SQL: Subscriber Engagement Score",
    desc_es:
      "Construye un score de engagement consultando _Sent, _Open y _Click en Automation Studio.",
    desc_en:
      "Build an engagement score by querying _Sent, _Open and _Click in Automation Studio.",
    duration: "9 min",
    date: "Feb 2025",
    viewsMin: 900,
    viewsMax: 2500,
    hot: false,
    tags: ["#sql", "#engagement", "#dataviews", "#scoring"],
    featured: true,
  },
  {
    id: "sql-joins",
    category: "sql",
    level: "advanced",
    url: "/sql-joins",
    title_es: "SQL: JOINs avanzados en Query Activities",
    title_en: "SQL: Advanced JOINs in Query Activities",
    desc_es:
      "LEFT JOIN, INNER JOIN y subconsultas para cruzar Data Extensions y Data Views en una sola query.",
    desc_en:
      "LEFT JOIN, INNER JOIN and subqueries to cross Data Extensions and Data Views in a single query.",
    duration: "10 min",
    date: "Mar 2025",
    viewsMin: 800,
    viewsMax: 2200,
    hot: false,
    tags: ["#sql", "#joins", "#subqueries"],
  },
  {
    id: "auto-filedrop",
    category: "automation",
    level: "intermediate",
    url: "/auto-filedrop",
    title_es: "Automation Studio: Patrón File Drop",
    title_en: "Automation Studio: File Drop Pattern",
    desc_es:
      "Configura un flujo automático que se dispara cuando un archivo llega al FTP de SFMC.",
    desc_en:
      "Set up an automatic flow triggered when a file arrives at the SFMC FTP.",
    duration: "6 min",
    date: "Mar 2025",
    viewsMin: 600,
    viewsMax: 1800,
    hot: false,
    tags: ["#automation", "#filedrop", "#ftp"],
  },
  {
    id: "jb-api-entry",
    category: "journey",
    level: "advanced",
    url: "/jb-api-entry",
    title_es: "Journey Builder: API Entry Event",
    title_en: "Journey Builder: API Entry Event",
    desc_es:
      "Dispara journeys en tiempo real desde sistemas externos usando la Event Definition API.",
    desc_en:
      "Trigger journeys in real time from external systems using the Event Definition API.",
    duration: "11 min",
    date: "Apr 2025",
    viewsMin: 1500,
    viewsMax: 4000,
    hot: true,
    tags: ["#journey", "#api-entry", "#event-definition"],
  },
  {
    id: "cp-auth",
    category: "cloudpages",
    level: "advanced",
    url: "/cp-auth",
    title_es: "Cloud Pages: Sistema de Login con Tokens",
    title_en: "Cloud Pages: Token-Based Login System",
    desc_es:
      "Implementa autenticación segura en Cloud Pages usando tokens únicos almacenados en Data Extensions.",
    desc_en:
      "Implement secure authentication in Cloud Pages using unique tokens stored in Data Extensions.",
    duration: "14 min",
    date: "Apr 2025",
    viewsMin: 1000,
    viewsMax: 3000,
    hot: true,
    tags: ["#cloudpages", "#auth", "#tokens", "#security"],
  },
  {
    id: "inno-ai",
    category: "innovations",
    level: "advanced",
    url: "/inno-ai",
    title_es: "Personalización con IA: GPT + AMPscript",
    title_en: "AI Personalization: GPT + AMPscript",
    desc_es:
      "Genera contenido de email personalizado con OpenAI GPT-4 y renderízalo con AMPscript en tus envíos.",
    desc_en:
      "Generate personalized email content with OpenAI GPT-4 and render it with AMPscript in your sends.",
    duration: "15 min",
    date: "Apr 2025",
    viewsMin: 2500,
    viewsMax: 6000,
    hot: true,
    tags: ["#innovations", "#ai", "#gpt", "#personalization"],
  },
  {
    id: "resources-links",
    category: "resources",
    level: "beginner",
    url: "/resources-links",
    title_es: "Recursos esenciales de SFMC",
    title_en: "Essential SFMC Resources",
    desc_es:
      "Documentación oficial, herramientas de debugging, comunidades y cursos recomendados para SFMC.",
    desc_en:
      "Official documentation, debugging tools, communities and recommended courses for SFMC.",
    duration: "3 min",
    date: "Jan 2025",
    viewsMin: 600,
    viewsMax: 1800,
    hot: false,
    tags: ["#resources", "#documentation", "#tools"],
  },
  {
    id: "next-datacloud-segments",
    category: "mc-next",
    level: "intermediate",
    url: "/next-datacloud-segments",
    title_es: "Data Cloud: Segmentación en Tiempo Real y Activación",
    title_en: "Data Cloud: Real-Time Segmentation & Activation",
    desc_es:
      "Unifica perfiles con Identity Resolution, crea Calculated Insights y activa segmentos sin queries SQL en Automation Studio.",
    desc_en:
      "Unify profiles with Identity Resolution, build Calculated Insights and activate segments without SQL in Automation Studio.",
    duration: "10 min",
    date: "May 2025",
    viewsMin: 3200,
    viewsMax: 8500,
    hot: true,
    tags: ["#datacloud", "#segmentation", "#dmo", "#realtime"],
    featured: true,
  },
  {
    id: "next-agentforce-campaigns",
    category: "mc-next",
    level: "advanced",
    url: "/next-agentforce-campaigns",
    title_es: "Agentforce for Marketing: Campañas Autónomas y Prompt Studio",
    title_en: "Agentforce for Marketing: Autonomous Campaigns & Prompt Studio",
    desc_es:
      "Configura agentes de IA autónomos con Topics, Actions y Prompt Templates conectados en tiempo real a Data Cloud.",
    desc_en:
      "Build autonomous AI marketing agents with Topics, Actions and Prompt Templates grounded with live Data Cloud.",
    duration: "12 min",
    date: "May 2025",
    viewsMin: 4100,
    viewsMax: 9200,
    hot: true,
    tags: ["#agentforce", "#ai", "#autonomous-campaigns", "#einstein"],
    featured: true,
  },
];
